/** @type {import('tailwindcss').Config} */
const scaleMedia =
  "(min-width: 668px) and (max-aspect-ratio: 13 / 9) and (max-height: 499px), (min-width: 668px) and (max-aspect-ratio: 13 / 9) and (max-width: 1440px), (min-width: 668px) and (min-height: 416px) and (max-height: 499px), (min-width: 668px) and (min-height: 416px) and (max-width: 1440px), (min-width: 980px) and (max-height: 499px), (min-width: 980px) and (max-width: 1440px)";
export default {
  content: ["./*.{html,js}", "./src/**/*.{html,js}"],
  theme: {
    screens: {
      scaleMedia: {
        raw: `${scaleMedia}`,
      },
      sm: {
        raw: `${scaleMedia}, (min-width: 1440px)`,
      },
      md: "768px",
      "2md": "900px",
      lg: "1024px",
      xl: "1280px",
      mainBloks: "1450px",
      "2xl": "1536px",
    },
    colors: {
      transparent: "transparent",
      black: {
        DEFAULT: "#101010",
        modal: "rgba(0, 0, 0, 0.6)",
        100: "#191919",
        90: "#212121",
        80: "#282828",
        70: "#373737",
        60: "#3A3A3A",
        50: "#5C5C5C",
        40: "#767676",
        30: "#828282",
        20: "#ACACAC",
        10: "#D3D3D3",
      },
      white: {
        100: "#FFFFFF",
        80: "#B7B7B7",
      },
      orange: {
        100: "#FF4E16",
        80: "#FC6F43",
      },
      red: {
        100: "#E71730",
      },
    },
    fontSize: {
      0: [
        "calc(var(--scale-text-rem) * 9.6)",
        {
          lineHeight: "1em",
          letterSpacing: "-0.04em",
          fontWeight: "400",
        },
      ],
      0.4: [
        "calc(var(--scale-text-rem) * 6.4)",
        {
          lineHeight: "1em",
          letterSpacing: "-0.04em",
          fontWeight: "400",
        },
      ],
      0.5: [
        "calc(var(--scale-text-rem) * 4.8)",
        {
          lineHeight: "1em",
          letterSpacing: "0.01em",
          fontWeight: "400",
        },
      ],
      1: [
        "calc(var(--scale-text-rem) * 3.8)",
        {
          lineHeight: "1.2em",
          letterSpacing: "-0.01em",
          fontWeight: "300",
        },
      ],
      2: [
        "calc(var(--scale-text-rem) * 3)",
        {
          lineHeight: "1.2em",
          letterSpacing: "-0.01em",
          fontWeight: "300",
        },
      ],
      3: [
        "calc(var(--scale-text-rem) * 3)",
        {
          lineHeight: "1.2em",
          letterSpacing: "-0.01em",
          fontWeight: "400",
        },
      ],
      4: [
        "calc(var(--scale-text-rem) * 2.7)",
        {
          lineHeight: "1.35em",
          letterSpacing: "-0.01em",
          fontWeight: "400",
        },
      ],
      5: [
        "calc(var(--scale-text-rem) * 2.7)",
        {
          lineHeight: "1.35em",
          letterSpacing: "-0.01em",
          fontWeight: "400",
        },
      ],
      6: [
        "calc(var(--scale-text-rem) * 2.3)",
        {
          lineHeight: "1.35em",
          letterSpacing: "-0.01em",
          fontWeight: "300",
        },
      ],
      7: [
        "calc(var(--scale-text-rem) * 2)",
        {
          lineHeight: "1.35em",
          letterSpacing: "-0.01em",
          fontWeight: "300",
        },
      ],
      8: [
        "calc(var(--scale-text-rem) * 1.7)",
        {
          lineHeight: "1.45em",
          fontWeight: "300",
        },
      ],
      9: [
        "calc(var(--scale-text-rem) * 1.7)",
        {
          lineHeight: "1.35em",
          letterSpacing: "0.01em",
          fontWeight: "400",
        },
      ],
      10: [
        "calc(var(--scale-text-rem) * 1.5)",
        {
          lineHeight: "1.45em",
          fontWeight: "300",
        },
      ],
      11: [
        "calc(var(--scale-text-rem) * 1.3)",
        {
          lineHeight: "1.45em",
          letterSpacing: "0",
          fontWeight: "400",
        },
      ],
      12: [
        "38px",
        {
          lineHeight: "1.2em",
          letterSpacing: "-0.01em",
          fontWeight: "400",
        },
      ],
      12.1: [
        "48px",
        {
          lineHeight: "1em",
          letterSpacing: "-0.01em",
          fontWeight: "400",
        },
      ],
      13: [
        "30px",
        {
          lineHeight: "1.2em",
          fontWeight: "400",
        },
      ],
      14: [
        "23px",
        {
          lineHeight: "1.35em",
          letterSpacing: "-0.01em",
          fontWeight: "400",
        },
      ],
      15: [
        "20px",
        {
          lineHeight: "1.35em",
          letterSpacing: "-0.01em",
          fontWeight: "400",
        },
      ],
      16: [
        "17px",
        {
          lineHeight: "1.45em",
          fontWeight: "400",
        },
      ],
      17: [
        "17px",
        {
          lineHeight: "1.45em",
          fontWeight: "500",
        },
      ],
      18: [
        "15px",
        {
          lineHeight: "1.45em",
          fontWeight: "400",
        },
      ],
      19: [
        "15px",
        {
          lineHeight: "1.2em",
          fontWeight: "500",
          letterSpacing: "0.01em",
        },
      ],
      20: [
        "13px",
        {
          lineHeight: "1.45em",
          fontWeight: "500",
        },
      ],
      21: [
        "12px",
        {
          lineHeight: "1.2em",
          fontWeight: "500",
        },
      ],
    },
    height: {
      screen: "var(--doc-height, 100vh)",
      full: "100%",
      auto: "auto",
      fit: "fit-content",
      516: "calc(var(--scale-rem) * 51.6)",
      125: "calc(var(--scale-rem) * 12.5)",
      57: "calc(var(--scale-rem) * 5.7)",
      52: "calc(var(--scale-rem) * 5.2)",
      32: "calc(var(--scale-rem) * 3.2)",
      24: "calc(var(--scale-rem) * 2.4)",
      16: "calc(var(--scale-rem) * 1.6)",
      1: "1px",
    },
    backgroundSize: {
      auto: "auto",
      cover: "cover",
      contain: "contain",
      0: "0px",
    },
    extend: {
      aspectRatio: {
        "589/448": "589 / 448",
        "456/287": "456 / 287",
        "351/199": "351 / 199",
        "333/221": "333 / 221",
        "320/247": "320 / 247",
        "228/125": "228 / 125",
        "53/40": "53 / 40",
        "57/41": "57 / 41",
        "32/25": "32 / 25",
        "16/11": "16 / 11",
      },
      spacing: {
        589: "calc(var(--scale-rem) * 58.9)",
        333: "calc(var(--scale-rem) * 33.3)",
        252: "calc(var(--scale-rem) * 25.2)",
        200: "calc(var(--scale-rem) * 20)",
        193: "calc(var(--scale-rem) * 19.3)",
        187: "calc(var(--scale-rem) * 18.7)",
        182: "calc(var(--scale-rem) * 18.2)",
        176: "calc(var(--scale-rem) * 17.6)",
        168: "calc(var(--scale-rem) * 16.8)",
        160: "calc(var(--scale-rem) * 16)",
        150: "calc(var(--scale-rem) * 15)",
        140: "calc(var(--scale-rem) * 14)",
        138: "calc(var(--scale-rem) * 13.8)",
        133: "calc(var(--scale-rem) * 13.3)",
        125: "calc(var(--scale-rem) * 12.5)",
        123: "calc(var(--scale-rem) * 12.3)",
        120: "calc(var(--scale-rem) * 12)",
        119: "calc(var(--scale-rem) * 11.9)",
        116: "calc(var(--scale-rem) * 11.6)",
        115: "calc(var(--scale-rem) * 11.5)",
        113: "calc(var(--scale-rem) * 11.3)",
        112: "calc(var(--scale-rem) * 11.2)",
        105: "calc(var(--scale-rem) * 10.5)",
        104: "calc(var(--scale-rem) * 10.4)",
        102: "calc(var(--scale-rem) * 10.2)",
        100: "calc(var(--scale-rem) * 10)",
        95: "calc(var(--scale-rem) * 9.5)",
        91: "calc(var(--scale-rem) * 9.1)",
        86: "calc(var(--scale-rem) * 8.6)",
        85: "calc(var(--scale-rem) * 8.5)",
        84: "calc(var(--scale-rem) * 8.4)",
        81: "calc(var(--scale-rem) * 8.1)",
        80: "calc(var(--scale-rem) * 8)",
        79: "calc(var(--scale-rem) * 7.9)",
        77: "calc(var(--scale-rem) * 7.7)",
        74: "calc(var(--scale-rem) * 7.4)",
        70: "calc(var(--scale-rem) * 7)",
        69: "calc(var(--scale-rem) * 6.9)",
        65: "calc(var(--scale-rem) * 6.5)",
        64: "calc(var(--scale-rem) * 6.4)",
        63: "calc(var(--scale-rem) * 6.3)",
        61: "calc(var(--scale-rem) * 6.1)",
        60: "calc(var(--scale-rem) * 6)",
        59: "calc(var(--scale-rem) * 5.9)",
        58: "calc(var(--scale-rem) * 5.8)",
        57: "calc(var(--scale-rem) * 5.7)",
        56: "calc(var(--scale-rem) * 5.6)",
        52: "calc(var(--scale-rem) * 5.2)",
        50: "calc(var(--scale-rem) * 5)",
        49: "calc(var(--scale-rem) * 4.9)",
        48: "calc(var(--scale-rem) * 4.8)",
        47: "calc(var(--scale-rem) * 4.7)",
        46: "calc(var(--scale-rem) * 4.6)",
        40: "calc(var(--scale-rem) * 4)",
        38: "calc(var(--scale-rem) * 3.8)",
        36: "calc(var(--scale-rem) * 3.6)",
        35: "calc(var(--scale-rem) * 3.5)",
        34: "calc(var(--scale-rem) * 3.4)",
        32: "calc(var(--scale-rem) * 3.2)",
        30: "calc(var(--scale-rem) * 3)",
        29: "calc(var(--scale-rem) * 2.9)",
        28: "calc(var(--scale-rem) * 2.8)",
        26: "calc(var(--scale-rem) * 2.6)",
        25: "calc(var(--scale-rem) * 2.5)",
        24: "calc(var(--scale-rem) * 2.4)",
        23: "calc(var(--scale-rem) * 2.3)",
        22: "calc(var(--scale-rem) * 2.2)",
        20: "calc(var(--scale-rem) * 2)",
        18: "calc(var(--scale-rem) * 1.8)",
        17: "calc(var(--scale-rem) * 1.7)",
        16: "calc(var(--scale-rem) * 1.6)",
        15: "calc(var(--scale-rem) * 1.5)",
        14: "calc(var(--scale-rem) * 1.4)",
        13: "calc(var(--scale-rem) * 1.3)",
        12: "calc(var(--scale-rem) * 1.2)",
        11: "calc(var(--scale-rem) * 1.1)",
        10: "calc(var(--scale-rem) * 1)",
        9: "calc(var(--scale-rem) * 0.9)",
        8: "calc(var(--scale-rem) * 0.8)",
        7: "calc(var(--scale-rem) * 0.7)",
        6: "calc(var(--scale-rem) * 0.6)",
        5: "calc(var(--scale-rem) * 0.5)",
        4: "calc(var(--scale-rem) * 0.4)",
        3: "calc(var(--scale-rem) * 0.3)",
        2: "calc(var(--scale-rem) * 0.2)",
        1: "1px",
      },
      backgroundImage: {
        inherit: "inherit",
      },
    },
  },

  plugins: [],
};
